- index.html
wasn't sure how to regenerate the `index.html` from `params.json` - didn't see a Markdown file in the `gh-pages` nor `master` branch
> link to WebVR Slack from Misc Links section

- index.html
Destination page will add enabling information shortly.
> Add Samsung Internet for Gear VR information

- index.html
Hi @toji, I'm part of @torgo's new dev rel team for Samsung Internet. Our developer site just had a revamp and our old URLs have disappeared. Please would it be OK to update the link to this?
> Update Samsung Internet for Gear VR link

- get-chrome/index.html
- index.html
- samples/index.html
- stylesheets/stylesheet.css
see previews here:
* https://cvan.io/webvr.info/
* https://cvan.io/webvr.info/samples/
* https://cvan.io/webvr.info/get-chrome/
> fix styles on Samples page + various anchors (fixes #24)

- index.html
Not sure if this is appropriate, just thought this might be a relevant resource to get started.
> add link to a-frame

- samples/js/third-party/wglu/wglu-debug-geometry.js
This is mainly intended for the controller demo so that it looks
a bit more three-dimensional.
> Implement simple half-lambert shading for debug geometry

- samples/02-stereo-rendering.html
- samples/03-vr-presentation.html
- samples/04-simple-mirroring.html
- samples/04b-simple-mirroring-2.html
- samples/08-dynamic-resolution.html
- samples/js/vr-cube-sea.js
- samples/test-canvas-attributes.html
This helps make dropped frames more visible because reprojection can't fix
these. They'll show jumps or double vision effects.
(It's also a sanity check for http://crbug.com/669594 with its mis-scaled timestamp.)
> Add a few moving "hero cubes" to the cube sea

- samples/js/third-party/wglu/wglu-stats.js
This makes dropped frames much more visible. In the graph 59fps
looks very similar to 60fps, but in VR it's likely to mean
a very degraded experience.
> Update the FPS counter to show a min-to-average FPS range

- samples/03-vr-presentation.html
- samples/04b-simple-mirroring-2.html
> Add timestamp for render

- samples/01-vr-input.html
- samples/02-stereo-rendering.html
- samples/03-vr-presentation.html
- samples/04-simple-mirroring.html
- samples/04b-simple-mirroring-2.html
- samples/05-room-scale.html
- samples/06-vr-audio.html
- samples/07-advanced-mirroring.html
- samples/08-dynamic-resolution.html
- samples/XX-360-panorama.html
- samples/XX-vr-controllers.html
- samples/test-slow-render.html
User should rely on platform method for doing, want to discourage anyone relying upon, etc.
-> https://github.com/w3c/webvr/issues/189
> Remove display/usage of resetPose, as deprecated

- samples/js/third-party/wglu/wglu-stats.js
@klausw, Is this more-or-less what you had in mind?
> Prevent one or two unusually fast frames from skewing the FPS average.

- index.html
URL moved according to destination
> Update Mozilla's link

- developers/index.html
> New link locations

- index.html
plus remove old 301 redirect uri.
> HTTPS all the things

- samples/XX-vr-controllers.html
- samples/js/third-party/wglu/wglu-debug-geometry.js
Also shows angular velocity and linear acceleration for
the headset if available.
Includes new drawArrow and drawCoordinateAxes methods
for debug geometry to help visualize vectors in a given
transform matrix's reference frame.
> Update XX-vr-controllers to show angular velocity + linear acceleration

- samples/00-hello-webvr.html
- samples/01-vr-input.html
- samples/02-stereo-rendering.html
- samples/03-vr-presentation.html
- samples/04-simple-mirroring.html
- samples/04b-simple-mirroring-2.html
- samples/05-room-scale.html
- samples/06-vr-audio.html
- samples/07-advanced-mirroring.html
- samples/08-dynamic-resolution.html
- samples/XX-360-panorama.html
- samples/XX-vr-controllers.html
- samples/test-canvas-attributes.html
- samples/test-slow-render.html
- samples/test-vr-links.html
to not expire while 58 is still stable release
> Update Chrome 58 origin trial

- samples/js/third-party/wglu/wglu-url.js
- samples/js/vr-cube-sea.js
- samples/test-slow-render.html
See the two patches with latency patch support and a few more tunable parameters. Not sure if it's actually very useful to make these available outside the slow-render app, for now I think making this one more tunable may be more useful.
> Klausw latencypatch

- samples/XX-360-video.html
This is used to change video for testing purpose.
@toji, PTAL. Thanks!
> Support videoUrl parameter in 360 video sample

- developers/index.html
It was already on the homepage... adding references on the Developers page too.
> Added references to Microsoft Edge as a supported WebVR browser

- samples/js/vr-panorama.js
Realized I introduced a redundant line of code. Have removed extra line and added comment as to the purpose of the line to prevent its being overlooked again.
> Remove redundant line of code

- samples/index.html
- samples/test-slow-render.html
Adding a test page that supplies no frames so testers can see what will happen in that event.
> Add test functionality for no frames

- developers/index.html
Added link to React VR website
> Added ReactVR

- developers/index.html
- index.html
Seamless way to to consume WebVR with curated links and not needing to leave the headset or type in URLs!
> Add links to Supermedium for Vive/Rift/WMR.

- developers/index.html
- index.html
> fix dead links (fixes #96); update copy to reflect most of latest and current information (fixes #95 and more)

- developers/index.html
- index.html
Added on Daydream, Oculus Go and Vive port for Firefox Reality on browser's list
Added Firefox Reality on developer section
> Added Firefox Reality

- developers/index.html
- stylesheets/stylesheet.css
follow-up changes to PR #101 
<hr>
> improve style of bulleted lists

- samples/js/third-party/webvr-polyfill.js
Fixes issue #105 (rapid spinning), and adds Pixel 2/3 + more devices.
> Update polyfill to v0.10.10
